// Generated by CoffeeScript 1.6.3
(function() {
  var Flying, GameOverScene, GameScene, Hoge, Money, Sign, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  core = {};

  Money = [["10.png", 10], ["100.png", 100], ["500.png", 500]];

  Flying = (function(_super) {
    __extends(Flying, _super);

    function Flying(money) {
      Flying.__super__.constructor.call(this, 173, 173);
      this.image = core.assets[money[0]];
      this.vx = 0;
      this.vy = 0;
      this.length = 0;
      this.isTouched = false;
      this.isTouched = false;
      this.moveCenterTo(HQ_GAME_WIDTH / 2, HQ_GAME_HEIGHT - 100);
      this.score = money[1];
    }

    Flying.prototype.moveCenterTo = function(x, y) {
      this.x = x - this.width / 2;
      return this.y = y - this.height / 2;
    };

    Flying.prototype.hasFlied = function() {
      return this.isTouched;
    };

    Flying.prototype.ontouchstart = function(e) {
      this.touchstartX = e.x;
      return this.touchstartY = e.y;
    };

    Flying.prototype.ontouchend = function(e) {
      var dx, dy;
      if (!this.hasFlied()) {
        this.isTouched = true;
        this.touchendX = e.x;
        this.touchendY = e.y;
        dx = this.touchendX - this.touchstartX;
        dy = this.touchendY - this.touchstartY;
        this.vx = dx / 10;
        return this.vy = dy / 10;
      }
    };

    Flying.prototype.onenterframe = function() {
      var dx, dy;
      dx = this.x + this.vx;
      dy = this.y + this.vy;
      if (this.isTouched) {
        this.vy += 1;
        if (this.vy < 0) {
          this.length -= this.vy;
        } else if (this.vy > 0) {
          this.length += this.vy;
        }
        this.scaleX = 1 - this.length * 0.0005;
        this.scaleY = 1 - this.length * 0.0005;
      }
      if (0 < dx && dx < HQ_GAME_WIDTH && dy < HQ_GAME_HEIGHT) {
        this.x += this.vx;
        return this.y += this.vy;
      } else if (!this.isTrashed) {
        return this.dispatchEvent(new Event("out"));
      }
    };

    return Flying;

  })(Sprite);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["title.png"];
      this.addChild(this.bg);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.gameScene = new GameScene();
      return core.replaceScene(core.gameScene);
    };

    return TitleScene;

  })(Scene);

  Hoge = (function(_super) {
    __extends(Hoge, _super);

    function Hoge() {
      Hoge.__super__.constructor.call(this, 210, 80);
      this.moveTo(535, 100);
    }

    return Hoge;

  })(Sprite);

  Sign = (function(_super) {
    __extends(Sign, _super);

    function Sign() {
      Sign.__super__.constructor.call(this, 125, 71);
      this.image = core.assets["left.png"];
      this.moveTo(1100, 150);
    }

    return Sign;

  })(Sprite);

  GameScene = (function(_super) {
    __extends(GameScene, _super);

    function GameScene() {
      GameScene.__super__.constructor.call(this);
      this.length = 0;
      this.v = 0;
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game.png"];
      this.addChild(this.bg);
      this.hoge = new Hoge();
      this.addChild(this.hoge);
      this.addTrash();
      this.label = new Label(this.v.toString());
      this.label.font = "48px Serif";
      this.label.color = "black";
      this.label.x = 1100;
      this.label.y = 60;
      this.addChild(this.label);
      this.count = 10;
      this.countLabel = new Label(this.count.toString());
      this.countLabel.width = 220;
      this.countLabel.textAlign = "center";
      this.countLabel.moveTo(0, 58);
      this.countLabel.font = "48px Serif";
      this.countLabel.color = "rgb(24, 24, 24)";
      this.addChild(this.countLabel);
      this.lengthLabel = new Label(this.length.toString());
      this.lengthLabel.width = 220;
      this.lengthLabel.textAlign = "center";
      this.lengthLabel.moveTo(0, 195);
      this.lengthLabel.font = "48px Serif";
      this.lengthLabel.color = "rgb(24, 24, 24)";
      this.addChild(this.lengthLabel);
      this.sign = new Sign();
      this.addChild(this.sign);
    }

    GameScene.prototype.addTrash = function() {
      var _this = this;
      this.flying = new Flying(Money[Math.floor(Math.random() * 3)]);
      this.flying;
      this.addChild(this.flying);
      return this.flying.addEventListener("out", function() {
        core.gameOverScene = new GameOverScene(0);
        return core.replaceScene(core.gameOverScene);
      });
    };

    GameScene.prototype.onenterframe = function() {
      if (this.count === 0) {
        if (this.length > 2000) {
          core.gameOverScene = new GameOverScene(1);
          core.replaceScene(core.gameOverScene);
        } else {
          core.gameOverScene = new GameOverScene(0);
          core.replaceScene(core.gameOverScene);
        }
      }
      this.v = Math.sin(core.frame / 100) * 3;
      this.label.text = this.v.toFixed(2);
      if (0 < this.v) {
        this.sign.image = core.assets["right.png"];
      } else {
        this.sign.image = core.assets["left.png"];
      }
      if (this.flying.hasFlied()) {
        this.flying.x += this.v;
      }
      if (0 < this.flying.vy && this.flying.intersect(this.hoge)) {
        this.length += this.flying.score;
        this.lengthLabel.text = this.length.toString();
        this.removeChild(this.flying);
        delete this.flying;
        this.count--;
        this.countLabel.text = this.count.toString();
        return this.addTrash();
      }
    };

    return GameScene;

  })(Scene);

  GameOverScene = (function(_super) {
    __extends(GameOverScene, _super);

    function GameOverScene(score) {
      GameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      if (score === 0) {
        this.bg.image = core.assets["game_over1.png"];
      } else {
        this.bg.image = core.assets["game_over2.png"];
      }
      this.addChild(this.bg);
    }

    GameOverScene.prototype.ontouchstart = function() {
      return core.replaceScene(core.titleScene);
    };

    return GameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
    assets = [];
    assets.push("title.png");
    assets.push("game.png");
    assets.push("game_over1.png");
    assets.push("game_over2.png");
    assets.push("100.png");
    assets.push("10.png");
    assets.push("500.png");
    assets.push("right.png");
    assets.push("left.png");
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
