// Generated by CoffeeScript 1.6.3
(function() {
  var CountDownTimer, GameOverScene, GameScene, Shaking, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  core = {};

  CountDownTimer = (function(_super) {
    __extends(CountDownTimer, _super);

    function CountDownTimer(sec) {
      CountDownTimer.__super__.constructor.call(this);
      this.frame = sec * core.fps;
      this.startAt = Infinity;
    }

    CountDownTimer.prototype.start = function() {
      return this.startAt = core.frame;
    };

    CountDownTimer.prototype.isStarted = function() {
      return this.startAt < core.frame;
    };

    CountDownTimer.prototype.remainingFrame = function() {
      return this.frame - core.frame + this.startAt;
    };

    CountDownTimer.prototype.remainingSec = function() {
      return this.remainingFrame() / core.fps;
    };

    CountDownTimer.prototype.onenterframe = function() {
      var e;
      this.text = this.remainingSec().toFixed(2);
      if (this.remainingFrame() === 0) {
        e = new Event("over");
        return this.dispatchEvent(e);
      }
    };

    return CountDownTimer;

  })(Label);

  Shaking = (function(_super) {
    __extends(Shaking, _super);

    function Shaking(x, y) {
      Shaking.__super__.constructor.call(this, x, y);
    }

    Shaking.prototype.endCondition = function() {
      return false;
    };

    Shaking.prototype.shake = function() {
      if (this.endCondition()) {
        return this.dispatchEvent(new Event("over"));
      } else {

      }
    };

    Shaking.prototype.ontouchmove = function(e) {
      var next;
      next = this.opacity - 0.01;
      if (next > 0.2) {
        return this.opacity = next;
      } else {
        return this.opacity = 0;
      }
    };

    return Shaking;

  })(Sprite);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["title.png"];
      this.addChild(this.bg);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.gameScene = new GameScene();
      return core.replaceScene(core.gameScene);
    };

    return TitleScene;

  })(Scene);

  GameScene = (function(_super) {
    __extends(GameScene, _super);

    function GameScene() {
      var _this = this;
      GameScene.__super__.constructor.call(this);
      this.length = 0;
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game.png"];
      this.addChild(this.bg);
      this.newDish();
      this.timer = new CountDownTimer(30);
      this.timer.font = "40px Serif";
      this.timer.color = "white";
      this.timer.moveTo(50, 100);
      this.timer.start();
      this.addChild(this.timer);
      this.label = new Label(this.length.toString());
      this.label.font = "40px Serif";
      this.label.moveTo(1150, 70);
      this.addChild(this.label);
      this.timer.addEventListener("over", function() {
        core.gameOverScene = new GameOverScene(_this.length);
        return core.replaceScene(core.gameOverScene);
      });
    }

    GameScene.prototype.succPath = function(e) {
      if (this.endCondition()) {
        ++this.length;
        this.newDish();
        return this.label.text = this.length.toString();
      }
    };

    GameScene.prototype.newDish = function() {
      var d, x, y;
      this.dish = new Sprite(578, 558);
      this.dish.image = core.assets["sara.png"];
      this.dish.moveTo(400, 100);
      this.addChild(this.dish);
      d = 100;
      x = 2 * d * Math.random() - d + 50;
      y = 2 * d * Math.random() - d + 50;
      this.taint1 = new Shaking(229, 175);
      this.taint1.image = core.assets["yogore1.png"];
      this.taint1.moveTo(HQ_GAME_WIDTH / 2, HQ_GAME_HEIGHT / 2);
      this.taint1.moveBy(x, y);
      this.addChild(this.taint1);
      this.taint2 = new Shaking(229, 175);
      this.taint2.image = core.assets["yogore2.png"];
      this.taint2.moveTo(HQ_GAME_WIDTH / 2, HQ_GAME_HEIGHT / 2);
      this.taint2.moveBy(-x, -y);
      return this.addChild(this.taint2);
    };

    GameScene.prototype.endCondition = function() {
      return this.taint1.opacity < 0.01 && this.taint2.opacity < 0.01;
    };

    GameScene.prototype.ontouchstart = function(e) {
      return this.succPath(e);
    };

    GameScene.prototype.ontouchmove = function(e) {
      return this.succPath(e);
    };

    return GameScene;

  })(Scene);

  GameOverScene = (function(_super) {
    __extends(GameOverScene, _super);

    function GameOverScene(score) {
      GameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game_over.png"];
      this.addChild(this.bg);
      this.label = new Label(score.toString());
      this.label.font = "80px Serif";
      this.label.color = "black";
      this.label.x = (HQ_GAME_WIDTH - this.label.width) / 2 + 150;
      this.label.y = (HQ_GAME_HEIGHT - this.label.height) / 2;
      this.addChild(this.label);
    }

    GameOverScene.prototype.ontouchstart = function() {
      return core.replaceScene(core.titleScene);
    };

    return GameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
    assets = [];
    assets.push("title.png");
    assets.push("game.png");
    assets.push("game_over.png");
    assets.push("sara.png");
    assets.push("sponge.png");
    assets.push("yogore1.png");
    assets.push("yogore2.png");
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
