// Generated by CoffeeScript 1.6.3
(function() {
  var CountUpTimer, GameOverScene, GameScene, Noboridai, Player, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  core = {};

  CountUpTimer = (function(_super) {
    __extends(CountUpTimer, _super);

    function CountUpTimer() {
      CountUpTimer.__super__.constructor.call(this, "0.00");
      this.startAt = Infinity;
    }

    CountUpTimer.prototype.start = function() {
      return this.startAt = core.frame;
    };

    CountUpTimer.prototype.currentFrame = function() {
      return core.frame - this.startAt;
    };

    CountUpTimer.prototype.currentSec = function() {
      return this.currentFrame() / core.fps;
    };

    CountUpTimer.prototype.onenterframe = function() {
      return this.text = this.currentSec().toFixed(2);
    };

    return CountUpTimer;

  })(Label);

  Noboridai = (function(_super) {
    __extends(Noboridai, _super);

    function Noboridai() {
      Noboridai.__super__.constructor.call(this, 724, 590);
      this.image = core.assets["noboridai.png"];
    }

    return Noboridai;

  })(Sprite);

  Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      Player.__super__.constructor.call(this, 203, 176);
      this.image = core.assets["player.png"];
      this.r = 0;
      this.v = 0;
      this.moveTo(this.r + 200, HQ_GAME_HEIGHT - this.r - 200);
    }

    Player.prototype.succ = function() {
      this.frame++;
      if (this.v <= 200) {
        return this.v += 5;
      }
    };

    Player.prototype.onenterframe = function() {
      var nextR;
      nextR = this.r + this.v;
      if (0 < nextR) {
        this.r = nextR;
        this.v -= 1.2;
        return this.moveTo(this.r + 200, HQ_GAME_HEIGHT - this.r - 200);
      }
    };

    return Player;

  })(Sprite);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["title.png"];
      this.addChild(this.bg);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.gameScene = new GameScene();
      return core.replaceScene(core.gameScene);
    };

    return TitleScene;

  })(Scene);

  GameScene = (function(_super) {
    __extends(GameScene, _super);

    function GameScene() {
      GameScene.__super__.constructor.call(this);
      this.length = 0;
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game.png"];
      this.addChild(this.bg);
      this.player = new Player();
      this.addChild(this.player);
      this.noboridai = new Noboridai();
      this.noboridai.moveTo(300, 100);
      this.addChild(this.noboridai);
      this.timer = new CountUpTimer();
      this.timer.color = "blue";
      this.timer.moveTo(100, 100);
      this.timer.start();
      this.addChild(this.timer);
    }

    GameScene.prototype.ontouchstart = function() {
      return this.player.succ();
    };

    GameScene.prototype.onenterframe = function() {
      if (this.player.r > 480) {
        core.gameOverScene = new GameOverScene(this.timer.currentSec());
        return core.replaceScene(core.gameOverScene);
      }
    };

    return GameScene;

  })(Scene);

  GameOverScene = (function(_super) {
    __extends(GameOverScene, _super);

    function GameOverScene(score) {
      GameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game_over.png"];
      this.addChild(this.bg);
      this.startAt = core.frame;
      this.label = new Label(score.toFixed(2).toString());
      this.label.witdh = 600;
      this.label.textAlign = "center";
      this.label.font = "80px Serif";
      this.label.color = "black";
      this.label.x = (HQ_GAME_WIDTH - this.label.width) / 2;
      this.label.y = (HQ_GAME_HEIGHT - this.label.height) / 2;
      this.addChild(this.label);
    }

    GameOverScene.prototype.ontouchstart = function() {
      if (this.startAt + core.fps < core.frame) {
        return core.replaceScene(core.titleScene);
      }
    };

    return GameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
    assets = [];
    assets.push("title.png");
    assets.push("game.png");
    assets.push("game_over.png");
    assets.push("noboridai.png");
    assets.push("player.png");
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
