// Generated by CoffeeScript 1.6.3
(function() {
  var Bar, BarList, GameScene, Ice, IceList, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  core = {};

  BarList = ["bar1.png", "bar2.png", "bar3.png", "bar4.png", "bar5.png", "bar6.png"];

  IceList = ["ice1.png", "ice2.png", "ice3.png", "ice4.png", "ice5.png", "ice6.png", "ice7.png", "ice8.png"];

  Bar = (function(_super) {
    __extends(Bar, _super);

    function Bar(option) {
      Bar.__super__.constructor.call(this, 1043, 102);
      this.image = core.assets[option];
      this.moveTo(120, 312);
    }

    return Bar;

  })(Sprite);

  Ice = (function(_super) {
    __extends(Ice, _super);

    function Ice(option) {
      Ice.__super__.constructor.call(this, 699, 373);
      this.image = core.assets[option];
      this.moveTo(85, 173);
      this.isAte = false;
    }

    Ice.prototype.ontouchstart = function() {
      return this.isAte = true;
    };

    return Ice;

  })(Sprite);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["title.png"];
      this.addChild(this.bg);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.gameScene = new GameScene();
      return core.replaceScene(core.gameScene);
    };

    return TitleScene;

  })(Scene);

  GameScene = (function(_super) {
    __extends(GameScene, _super);

    function GameScene() {
      var i, ice, _i;
      GameScene.__super__.constructor.call(this);
      this.length = 0;
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game.png"];
      this.addChild(this.bg);
      this.bar = new Bar(BarList[Math.floor(Math.random() * 6)]);
      this.addChild(this.bar);
      this.count = 0;
      this.ices = [];
      for (i = _i = 7; _i >= 0; i = --_i) {
        ice = new Ice(IceList[i]);
        this.ices.push(ice);
        this.addChild(ice);
      }
      this.isEnd = false;
    }

    GameScene.prototype.ontouchstart = function() {
      var i, _i;
      for (i = _i = 0; _i <= 7; i = ++_i) {
        if (this.ices[i].isAte) {
          this.removeChild(this.ices[i]);
          this.ices[i].isAte = false;
          this.count++;
        }
      }
      if (this.isEnd) {
        return core.replaceScene(core.titleScene);
      }
    };

    GameScene.prototype.onenterframe = function() {
      if (this.count === 8) {
        return this.isEnd = true;
      }
    };

    return GameScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
    assets = [];
    assets.push("title.png");
    assets.push("game.png");
    assets.push("bar1.png");
    assets.push("bar2.png");
    assets.push("bar3.png");
    assets.push("bar4.png");
    assets.push("bar5.png");
    assets.push("bar6.png");
    assets.push("ice1.png");
    assets.push("ice2.png");
    assets.push("ice3.png");
    assets.push("ice4.png");
    assets.push("ice5.png");
    assets.push("ice6.png");
    assets.push("ice7.png");
    assets.push("ice8.png");
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
