// Generated by CoffeeScript 1.6.3
(function() {
  var CountUpTimer, GameOverScene, GameScene, HowToScene, IaiBaseScene, MySprite, TeaSurface, Teabag, Teacup, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  core = {};

  CountUpTimer = (function(_super) {
    __extends(CountUpTimer, _super);

    function CountUpTimer() {
      CountUpTimer.__super__.constructor.call(this, "0.00");
      this.startAt = Infinity;
    }

    CountUpTimer.prototype.start = function() {
      return this.startAt = core.frame;
    };

    CountUpTimer.prototype.currentFrame = function() {
      return core.frame - this.startAt;
    };

    CountUpTimer.prototype.currentSec = function() {
      return this.currentFrame() / core.fps;
    };

    CountUpTimer.prototype.onenterframe = function() {
      return this.text = this.currentSec().toFixed(2);
    };

    return CountUpTimer;

  })(Label);

  IaiBaseScene = (function(_super) {
    __extends(IaiBaseScene, _super);

    function IaiBaseScene() {
      IaiBaseScene.__super__.constructor.call(this);
      this.fightsStartAt = [];
      this.fightsEndAt = [];
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game.png"];
      this.addChild(this.bg);
    }

    IaiBaseScene.prototype.pastFights = function() {
      var _this = this;
      return this.fightsStartAt.filter(function(startAt, index, fights) {
        return startAt < core.frame;
      });
    };

    IaiBaseScene.prototype.nextFight = function() {
      var endAt, startAt;
      startAt = core.frame + 1 + Math.floor(Math.random() * 4);
      endAt = startAt + 1;
      this.fightsStartAt.push(startAt);
      return this.fightsEndAt.push(endAt);
    };

    IaiBaseScene.prototype.isFighting = function() {
      var e, s;
      s = this.fightsStartAt[this.fightsStartAt.length - 1];
      e = this.fightsEndAt[this.fightsEndAt.length - 1];
      return s < core.frame && core.frame < e;
    };

    return IaiBaseScene;

  })(Scene);

  MySprite = (function(_super) {
    __extends(MySprite, _super);

    function MySprite() {
      MySprite.__super__.constructor.call(this, 300, 300);
    }

    MySprite.prototype.onenterframe = function() {};

    return MySprite;

  })(Sprite);

  Teacup = (function(_super) {
    __extends(Teacup, _super);

    function Teacup() {
      Teacup.__super__.constructor.call(this, 636, 332);
      this.image = core.assets["tea2.png"];
    }

    Teacup.prototype.onenterframe = function() {};

    return Teacup;

  })(Sprite);

  TeaSurface = (function(_super) {
    __extends(TeaSurface, _super);

    function TeaSurface() {
      TeaSurface.__super__.constructor.call(this, 383, 49);
      this.image = core.assets["tea4.png"];
      this.opacity = 0.2;
    }

    TeaSurface.prototype.onenterframe = function() {
      return this.opacity += 0.001;
    };

    return TeaSurface;

  })(Sprite);

  Teabag = (function(_super) {
    __extends(Teabag, _super);

    function Teabag() {
      Teabag.__super__.constructor.call(this);
      this.vy = 0;
      this.string = new Sprite(86, 349);
      this.string.image = core.assets["tea1.png"];
      this.bag = new Sprite(166, 145);
      this.bag.image = core.assets["tea3.png"];
      this.bag.moveTo(-60, 320);
      this.addChild(this.string);
      this.addChild(this.bag);
    }

    Teabag.prototype.startMove = function() {
      return this.vy = -9;
    };

    Teabag.prototype.onenterframe = function() {
      return this.y += this.vy;
    };

    return Teabag;

  })(Group);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["title.png"];
      this.addChild(this.bg);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.howToScene = new HowToScene();
      return core.pushScene(core.howToScene);
    };

    return TitleScene;

  })(Scene);

  HowToScene = (function(_super) {
    __extends(HowToScene, _super);

    function HowToScene() {
      HowToScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["how.png"];
      this.addChild(this.bg);
    }

    HowToScene.prototype.ontouchstart = function() {
      core.popScene();
      core.gameScene = new GameScene();
      return core.replaceScene(core.gameScene);
    };

    return HowToScene;

  })(Scene);

  GameScene = (function(_super) {
    __extends(GameScene, _super);

    function GameScene() {
      var teaX, teaY;
      GameScene.__super__.constructor.call(this);
      this.startAt = core.frame;
      this.touchedAt = core.frame;
      teaX = 300;
      teaY = 300;
      this.teaSurface = new TeaSurface();
      this.teaSurface.moveTo(teaX + 120, teaY);
      this.addChild(this.teaSurface);
      this.teabag = new Teabag();
      this.teabag.moveTo(teaX + 270, teaY - 200);
      this.addChild(this.teabag);
      this.teacup = new Teacup();
      this.teacup.moveTo(teaX, teaY);
      this.addChild(this.teacup);
    }

    GameScene.prototype.ontouchstart = function() {
      this.teabag.startMove();
      if (this.startAt === this.touchedAt) {
        return this.touchedAt = core.frame;
      }
    };

    GameScene.prototype.onenterframe = function() {
      if (this.startAt !== this.touchedAt) {
        if (this.touchedAt + 2 * core.fps < core.frame) {
          core.gameOverScene = new GameOverScene(this.touchedAt - this.startAt);
          return core.replaceScene(core.gameOverScene);
        }
      }
    };

    return GameScene;

  })(IaiBaseScene);

  GameOverScene = (function(_super) {
    __extends(GameOverScene, _super);

    function GameOverScene(score) {
      var c1, c2, c3;
      GameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.addChild(this.bg);
      c1 = core.fps * 6;
      c2 = core.fps * 9;
      c3 = core.fps * 12;
      if (score < c1) {
        this.bg.image = core.assets["game_over4.png"];
      } else if (score < c2) {
        this.bg.image = core.assets["game_over2.png"];
      } else if (score < c3) {
        this.bg.image = core.assets["game_over1.png"];
      } else {
        this.bg.image = core.assets["game_over3.png"];
      }
      this.label = new Label(score.toString());
      this.label.font = "80px Serif";
      this.label.color = "white";
      this.label.x = (HQ_GAME_WIDTH - this.label.width) / 2;
      this.label.y = (HQ_GAME_HEIGHT - this.label.height) / 2;
      this.addChild(this.label);
    }

    GameOverScene.prototype.ontouchstart = function() {
      return core.replaceScene(core.titleScene);
    };

    return GameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
    assets = [];
    assets.push("title.png");
    assets.push("game.png");
    assets.push("game_over1.png");
    assets.push("game_over2.png");
    assets.push("game_over3.png");
    assets.push("game_over4.png");
    assets.push("tea1.png");
    assets.push("tea2.png");
    assets.push("tea3.png");
    assets.push("tea4.png");
    assets.push("how.png");
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
