// Generated by CoffeeScript 1.6.3
(function() {
  var Dai, GameOverScene, GameScene, Player, TitleScene, TobiBan, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  core = {};

  Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      Player.__super__.constructor.call(this, 89, 114);
      this.image = core.assets["player.png"];
      this.moveTo(20, 530);
      this.vx = 3;
      this.vy = 0;
      this.isCharging = true;
      this.isJumped = false;
      this.isJumping = false;
    }

    Player.prototype.charge = function() {
      if (this.isCharging) {
        this.x += 3 * Math.sin(2.0 * core.frame);
        return this.vx++;
      }
    };

    Player.prototype.onenterframe = function() {
      if (this.age === 120) {
        this.isCharging = false;
      }
      if (this.age > 150) {
        this.moveBy(this.vx, this.vy);
      }
      if (this.isJumping) {
        this.vy += 2.3;
        if (this.y >= 530) {
          this.vy = 0;
          this.isJumping = false;
        }
      }
      if (this.x > HQ_GAME_WIDTH) {
        core.gameOverScene = new GameOverScene(1);
        return core.replaceScene(core.gameOverScene);
      }
    };

    return Player;

  })(Sprite);

  Dai = (function(_super) {
    __extends(Dai, _super);

    function Dai() {
      Dai.__super__.constructor.call(this, 97, 300);
      this.moveTo(1022, 375);
    }

    return Dai;

  })(Sprite);

  TobiBan = (function(_super) {
    __extends(TobiBan, _super);

    function TobiBan() {
      TobiBan.__super__.constructor.call(this, 140, 20);
      this.moveTo(750, 600);
    }

    return TobiBan;

  })(Sprite);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["title.png"];
      this.addChild(this.bg);
      this.titleLabel = new Label("LEVEL2");
      this.titleLabel.width = 600;
      this.titleLabel.textAlign = "center";
      this.titleLabel.moveTo(750, 30);
      this.titleLabel.font = "96px Sans-serif";
      this.titleLabel.color = "rgb(244, 244, 244)";
      this.addChild(this.titleLabel);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.gameScene = new GameScene();
      return core.replaceScene(core.gameScene);
    };

    return TitleScene;

  })(Scene);

  GameScene = (function(_super) {
    __extends(GameScene, _super);

    function GameScene() {
      GameScene.__super__.constructor.call(this);
      this.length = 0;
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game.png"];
      this.addChild(this.bg);
      this.player = new Player();
      this.addChild(this.player);
      this.dai = new Dai();
      this.addChild(this.dai);
      this.tobiBan = new TobiBan();
      this.addChild(this.tobiBan);
    }

    GameScene.prototype.onenterframe = function() {
      if (this.dai.intersect(this.player)) {
        core.gameOverScene = new GameOverScene(0);
        core.replaceScene(core.gameOverScene);
      }
      if (this.tobiBan.intersect(this.player)) {
        if (this.player.isJumping) {
          return this.player.vy = -40;
        } else {
          core.gameOverScene = new GameOverScene(0);
          return core.replaceScene(core.gameOverScene);
        }
      }
    };

    GameScene.prototype.ontouchstart = function() {
      if (this.player.isCharging) {
        this.player.charge();
      }
      if (!this.player.isCharging && !this.player.isJumped) {
        this.player.isJumped = true;
        this.player.vy = -20;
        return this.player.isJumping = true;
      }
    };

    return GameScene;

  })(Scene);

  GameOverScene = (function(_super) {
    __extends(GameOverScene, _super);

    function GameOverScene(score) {
      GameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      if (score === 0) {
        this.bg.image = core.assets["game_over1.png"];
      } else if (score === 1) {
        this.bg.image = core.assets["game_over2.png"];
      }
      this.addChild(this.bg);
    }

    GameOverScene.prototype.ontouchstart = function() {
      return core.replaceScene(core.titleScene);
    };

    return GameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
    assets = [];
    assets.push("title.png");
    assets.push("game.png");
    assets.push("game_over1.png");
    assets.push("game_over2.png");
    assets.push("player.png");
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
