// Generated by CoffeeScript 1.6.3
(function() {
  var Atari, CountUpTimer, GameOverScene, GameScene, Kao, LBMatsuge, LTMatsuge, MakeUp, RBMatsuge, RTMatsuge, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  core = {};

  Kao = [
    {
      image: "game1.png",
      lMatsuge: {
        x: 352,
        y: 301
      },
      rMatsuge: {
        x: 933,
        y: 301
      },
      lTop: true,
      rTop: true
    }, {
      image: "game2.png",
      lMatsuge: {
        x: 352,
        y: 301
      },
      rMatsuge: {
        x: 933,
        y: 429
      },
      lTop: true,
      rTop: false
    }, {
      image: "game3.png",
      lMatsuge: {
        x: 352,
        y: 429
      },
      rMatsuge: {
        x: 933,
        y: 301
      },
      lTop: false,
      rTop: true
    }, {
      image: "game4.png",
      lMatsuge: {
        x: 352,
        y: 429
      },
      rMatsuge: {
        x: 933,
        y: 429
      },
      lTop: false,
      rTop: false
    }
  ];

  CountUpTimer = (function(_super) {
    __extends(CountUpTimer, _super);

    function CountUpTimer() {
      CountUpTimer.__super__.constructor.call(this, "0.00");
      this.startAt = Infinity;
    }

    CountUpTimer.prototype.start = function() {
      return this.startAt = core.frame;
    };

    CountUpTimer.prototype.currentFrame = function() {
      return core.frame - this.startAt;
    };

    CountUpTimer.prototype.currentSec = function() {
      return this.currentFrame() / core.fps;
    };

    CountUpTimer.prototype.onenterframe = function() {
      return this.text = this.currentSec().toFixed(2);
    };

    return CountUpTimer;

  })(Label);

  Atari = (function(_super) {
    __extends(Atari, _super);

    function Atari() {
      Atari.__super__.constructor.call(this, 20, 20);
    }

    return Atari;

  })(Sprite);

  MakeUp = (function(_super) {
    __extends(MakeUp, _super);

    function MakeUp() {
      MakeUp.__super__.constructor.call(this, 808, 179);
      this.image = core.assets["makeup.png"];
      this.moveTo((HQ_GAME_WIDTH - this.width) / 2, (HQ_GAME_HEIGHT - this.height) / 2);
    }

    return MakeUp;

  })(Sprite);

  LTMatsuge = (function(_super) {
    __extends(LTMatsuge, _super);

    function LTMatsuge() {
      LTMatsuge.__super__.constructor.call(this, 254, 104);
      this.image = core.assets["lt_matuge.png"];
    }

    LTMatsuge.prototype.ontouchmove = function(e) {
      return this.moveTo(e.x - this.width / 2, e.y - this.height / 2);
    };

    return LTMatsuge;

  })(Sprite);

  RTMatsuge = (function(_super) {
    __extends(RTMatsuge, _super);

    function RTMatsuge() {
      RTMatsuge.__super__.constructor.call(this, 254, 104);
      this.image = core.assets["rt_matuge.png"];
    }

    RTMatsuge.prototype.ontouchmove = function(e) {
      return this.moveTo(e.x - this.width / 2, e.y - this.height / 2);
    };

    return RTMatsuge;

  })(Sprite);

  LBMatsuge = (function(_super) {
    __extends(LBMatsuge, _super);

    function LBMatsuge() {
      LBMatsuge.__super__.constructor.call(this, 200, 89);
      this.image = core.assets["lb_matuge.png"];
    }

    LBMatsuge.prototype.ontouchmove = function(e) {
      return this.moveTo(e.x - this.width / 2, e.y - this.height / 2);
    };

    return LBMatsuge;

  })(Sprite);

  RBMatsuge = (function(_super) {
    __extends(RBMatsuge, _super);

    function RBMatsuge() {
      RBMatsuge.__super__.constructor.call(this, 200, 89);
      this.image = core.assets["rb_matuge.png"];
    }

    RBMatsuge.prototype.ontouchmove = function(e) {
      return this.moveTo(e.x - this.width / 2, e.y - this.height / 2);
    };

    return RBMatsuge;

  })(Sprite);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["title.png"];
      this.addChild(this.bg);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.gameScene = new GameScene(Kao[Math.floor(Math.random() * 4)]);
      return core.replaceScene(core.gameScene);
    };

    return TitleScene;

  })(Scene);

  GameScene = (function(_super) {
    __extends(GameScene, _super);

    function GameScene(options) {
      GameScene.__super__.constructor.call(this);
      this.lTop = options.lTop;
      this.rTop = options.rTop;
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets[options.image];
      this.addChild(this.bg);
      this.lAtari = new Atari();
      this.addChild(this.lAtari);
      this.lAtari.moveTo(options.lMatsuge.x, options.lMatsuge.y);
      this.rAtari = new Atari();
      this.addChild(this.rAtari);
      this.rAtari.moveTo(options.rMatsuge.x, options.rMatsuge.y);
      this.ltMatsuge = new LTMatsuge();
      this.addChild(this.ltMatsuge);
      this.ltMatsuge.moveTo(Math.random() * (HQ_GAME_WIDTH - this.ltMatsuge.width), Math.random() * (HQ_GAME_HEIGHT - this.ltMatsuge.height));
      this.rtMatsuge = new RTMatsuge();
      this.addChild(this.rtMatsuge);
      this.rtMatsuge.moveTo(Math.random() * (HQ_GAME_WIDTH - this.rtMatsuge.width), Math.random() * (HQ_GAME_HEIGHT - this.rtMatsuge.height));
      this.lbMatsuge = new LBMatsuge();
      this.addChild(this.lbMatsuge);
      this.lbMatsuge.moveTo(Math.random() * (HQ_GAME_WIDTH - this.lbMatsuge.width), Math.random() * (HQ_GAME_HEIGHT - this.lbMatsuge.height));
      this.rbMatsuge = new RBMatsuge();
      this.addChild(this.rbMatsuge);
      this.rbMatsuge.moveTo(Math.random() * (HQ_GAME_WIDTH - this.rbMatsuge.width), Math.random() * (HQ_GAME_HEIGHT - this.rbMatsuge.height));
      this.ltAtari = new Atari();
      this.addChild(this.ltAtari);
      this.rtAtari = new Atari();
      this.addChild(this.rtAtari);
      this.lbAtari = new Atari();
      this.addChild(this.lbAtari);
      this.rbAtari = new Atari();
      this.addChild(this.rbAtari);
      this.timer = new CountUpTimer();
      this.timer.width = 180;
      this.timer.textAlign = "center";
      this.timer.moveTo(30, 75);
      this.timer.font = "48px Sans-serif";
      this.timer.color = "rgb(24, 24, 24)";
      this.makeUp = new MakeUp();
      this.addChild(this.makeUp);
    }

    GameScene.prototype.onenterframe = function() {
      if (this.age === 30) {
        this.timer.start();
        this.addChild(this.timer);
        this.removeChild(this.makeUp);
      }
      this.ltAtari.moveTo(this.ltMatsuge.x + 123, this.ltMatsuge.y + 46);
      this.rtAtari.moveTo(this.rtMatsuge.x + 113, this.rtMatsuge.y + 45);
      this.lbAtari.moveTo(this.lbMatsuge.x + 85, this.lbMatsuge.y + 15);
      this.rbAtari.moveTo(this.rbMatsuge.x + 90, this.rbMatsuge.y + 18);
      if (this.lTop && this.rTop) {
        if (this.ltAtari.intersect(this.lAtari)) {
          if (this.rtAtari.intersect(this.rAtari)) {
            core.gameOverScene = new GameOverScene(this.timer.currentSec());
            core.replaceScene(core.gameOverScene);
          }
        }
      }
      if (this.lTop && !this.rTop) {
        if (this.ltAtari.intersect(this.lAtari)) {
          if (this.rbAtari.intersect(this.rAtari)) {
            core.gameOverScene = new GameOverScene(this.timer.currentSec());
            core.replaceScene(core.gameOverScene);
          }
        }
      }
      if (!this.lTop && this.rTop) {
        if (this.lbAtari.intersect(this.lAtari)) {
          if (this.rtAtari.intersect(this.rAtari)) {
            core.gameOverScene = new GameOverScene(this.timer.currentSec());
            core.replaceScene(core.gameOverScene);
          }
        }
      }
      if (!this.lTop && !this.rTop) {
        if (this.lbAtari.intersect(this.lAtari)) {
          if (this.rbAtari.intersect(this.rAtari)) {
            core.gameOverScene = new GameOverScene(this.timer.currentSec());
            return core.replaceScene(core.gameOverScene);
          }
        }
      }
    };

    return GameScene;

  })(Scene);

  GameOverScene = (function(_super) {
    __extends(GameOverScene, _super);

    function GameOverScene(score) {
      GameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
      this.bg.image = core.assets["game_over.png"];
      this.addChild(this.bg);
      this.score = score.toFixed(2);
      this.scoreLabel = new Label(this.score.toString());
      this.scoreLabel.width = 300;
      this.scoreLabel.textAlign = "center";
      this.scoreLabel.moveTo((HQ_GAME_WIDTH - this.scoreLabel.width) / 2, 430);
      this.scoreLabel.font = "100px Sans-serif";
      this.scoreLabel.color = "rgb(230,230,230)";
      this.addChild(this.scoreLabel);
    }

    GameOverScene.prototype.ontouchstart = function() {
      return core.replaceScene(core.titleScene);
    };

    return GameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(HQ_GAME_WIDTH, HQ_GAME_HEIGHT);
    assets = [];
    assets.push("title.png");
    assets.push("game1.png");
    assets.push("game2.png");
    assets.push("game3.png");
    assets.push("game4.png");
    assets.push("game_over.png");
    assets.push("rt_matuge.png");
    assets.push("lt_matuge.png");
    assets.push("rb_matuge.png");
    assets.push("lb_matuge.png");
    assets.push("makeup.png");
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
